# Generated by Django 4.2.20 on 2025-04-10 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OperationalCost",
        ),
        migrations.RemoveField(
            model_name="regularemployeeprojectcost",
            name="employee",
        ),
        migrations.DeleteModel(
            name="ProvisionaryEmployeeProjectCost",
        ),
        migrations.DeleteModel(
            name="RegularEmployeeProjectCost",
        ),
    ]
