# Generated by Django 4.2.20 on 2025-04-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(
                help_text="Individual name",
                max_length=100,
                verbose_name="Employee Name",
            ),
        ),
    ]
