# Generated by Django 4.2.20 on 2025-05-01 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_alter_employee_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(
                help_text="Primary contact email",
                max_length=254,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="Email Address",
            ),
        ),
    ]
