# Generated by Django 4.2.20 on 2025-04-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vessel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mv",
            name="m_vessel",
            field=models.CharField(
                default=1, max_length=40, verbose_name="Motor Vessel Name"
            ),
            preserve_default=False,
        ),
    ]
