# Generated by Django 4.2.20 on 2025-04-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bankbook",
            old_name="reference",
            new_name="particulars",
        ),
        migrations.RenameField(
            model_name="cashbook",
            old_name="reference",
            new_name="particulars",
        ),
    ]
