# Generated by Django 4.2.20 on 2025-04-16 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_remove_cashbook_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankbook",
            name="current_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cashbook",
            name="current_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
            preserve_default=False,
        ),
    ]
