# Generated by Django 4.2.20 on 2025-05-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_bankbook_current_balance_cashbook_current_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("CURRENT", "Current Account"),
                    ("SAVINGS", "Savings Account"),
                    ("FIXED", "Fixed CREDIT"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bankbook",
            name="transaction_type",
            field=models.CharField(
                choices=[("CREDIT", "CREDIT"), ("DEBIT", "DEBIT")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="cashbook",
            name="transaction_type",
            field=models.CharField(
                choices=[("CREDIT", "CREDIT"), ("DEBIT", "DEBIT")], max_length=20
            ),
        ),
    ]
