# Generated by Django 4.2.20 on 2025-04-08 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official business or individual name",
                        max_length=100,
                        verbose_name="Client Name",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        help_text="Main point of contact",
                        max_length=100,
                        verbose_name="Primary Contact",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary contact email",
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, max_length=200, verbose_name="Full Address"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACT", "Active"),
                            ("INA", "Inactive"),
                            ("PRO", "Prospect"),
                            ("BLK", "Blacklisted"),
                        ],
                        default="PRO",
                        max_length=3,
                        verbose_name="Client Status",
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Tax Identification Number",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Internal Notes"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="clients_cli_name_5ab7bc_idx"),
                    models.Index(fields=["email"], name="clients_cli_email_56b9fc_idx"),
                    models.Index(
                        fields=["status"], name="clients_cli_status_ce0d15_idx"
                    ),
                ],
            },
        ),
    ]
