# Generated by Django 4.2.20 on 2025-04-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="client",
            name="clients_cli_status_ce0d15_idx",
        ),
        migrations.RemoveField(
            model_name="client",
            name="status",
        ),
        migrations.AddField(
            model_name="client",
            name="types",
            field=models.CharField(
                choices=[("LOC", "Local"), ("INT", "International")],
                default="INT",
                max_length=3,
                verbose_name="Client Types",
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["types"], name="clients_cli_types_34d7c0_idx"),
        ),
    ]
