# Generated by Django 4.2.20 on 2025-05-01 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_remove_client_clients_cli_status_ce0d15_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(
                help_text="Primary contact email",
                max_length=254,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="Email Address",
            ),
        ),
    ]
