# Generated by Django 4.2.20 on 2025-04-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("TK.", "Bangladeshi Taka"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        choices=[
                            (2025, 2025),
                            (2024, 2024),
                            (2023, 2023),
                            (2022, 2022),
                            (2021, 2021),
                            (2020, 2020),
                        ],
                        default=2025,
                        verbose_name="year",
                    ),
                ),
                ("bdt_equivalent", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
