# Generated by Django 4.2.20 on 2025-04-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "isfor",
                    models.CharField(
                        choices=[
                            ("I", "Invoice"),
                            ("PR", "Payroll_Regular"),
                            ("PC", "Payroll_Casual"),
                            ("CB", "Cash_Book"),
                            ("BB", "Bank_Book"),
                        ],
                        max_length=40,
                    ),
                ),
                ("src_code", models.TextField()),
                ("is_default", models.BooleanField(default=True)),
            ],
        ),
    ]
