# Generated by Django 4.2.20 on 2026-03-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_pdftemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyrate",
            name="year",
            field=models.IntegerField(
                choices=[
                    (2026, 2026),
                    (2025, 2025),
                    (2024, 2024),
                    (2023, 2023),
                    (2022, 2022),
                    (2021, 2021),
                ],
                default=2026,
                verbose_name="year",
            ),
        ),
    ]
