# Generated by Django 4.2.20 on 2025-04-10 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0002_alter_employee_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalExpenditure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expenditure_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular"),
                            ("PROVISIONAL", "Provisional"),
                            ("OPERATIONAL", "Operational"),
                        ],
                        max_length=20,
                        verbose_name="Type of Expenditure",
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK", "Bank Transfer"),
                            ("BKASH", "bKash"),
                            ("CHECK", "Check"),
                        ],
                        max_length=10,
                    ),
                ),
                ("receipt_number", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("escort", models.IntegerField(default=0)),
                ("mariner", models.IntegerField(default=0)),
                ("equipment", models.IntegerField(default=0)),
                ("speedboat", models.IntegerField(default=0)),
                ("others", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RegularExpenditure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expenditure_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular"),
                            ("PROVISIONAL", "Provisional"),
                            ("OPERATIONAL", "Operational"),
                        ],
                        max_length=20,
                        verbose_name="Type of Expenditure",
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK", "Bank Transfer"),
                            ("BKASH", "bKash"),
                            ("CHECK", "Check"),
                        ],
                        max_length=10,
                    ),
                ),
                ("receipt_number", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ot_hours", models.IntegerField(default=0)),
                ("ot_rate", models.IntegerField(default=50)),
                ("conveyance", models.IntegerField(default=0)),
                ("boat_fee", models.IntegerField(default=0)),
                ("fooding_fee", models.IntegerField(default=0)),
                ("hotel_fee", models.IntegerField(default=0)),
                ("night_allownce", models.IntegerField(default=0)),
                ("others", models.IntegerField(default=0)),
                ("paid_in_advance", models.IntegerField(default=0)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_costs_regular",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProvisionaryExpenditure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expenditure_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular"),
                            ("PROVISIONAL", "Provisional"),
                            ("OPERATIONAL", "Operational"),
                        ],
                        max_length=20,
                        verbose_name="Type of Expenditure",
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK", "Bank Transfer"),
                            ("BKASH", "bKash"),
                            ("CHECK", "Check"),
                        ],
                        max_length=10,
                    ),
                ),
                ("receipt_number", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fixed_amount", models.IntegerField(default=0)),
                ("ot_hours", models.IntegerField(default=0)),
                ("ot_rate", models.IntegerField(default=50)),
                ("conveyance", models.IntegerField(default=0)),
                ("boat_fee", models.IntegerField(default=0)),
                ("fooding_fee", models.IntegerField(default=0)),
                ("hotel_fee", models.IntegerField(default=0)),
                ("night_allownce", models.IntegerField(default=0)),
                ("others", models.IntegerField(default=0)),
                ("paid_in_advance", models.IntegerField(default=0)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_costs_provisionary",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
    ]
