# Generated by Django 4.2.20 on 2025-04-11 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_delete_operationalcost_and_more"),
        ("expenditure", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationalexpenditure",
            name="description",
        ),
        migrations.RemoveField(
            model_name="provisionaryexpenditure",
            name="description",
        ),
        migrations.RemoveField(
            model_name="regularexpenditure",
            name="description",
        ),
        migrations.AddField(
            model_name="operationalexpenditure",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_operation",
                to="projects.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="provisionaryexpenditure",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_provision",
                to="projects.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="regularexpenditure",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_regular",
                to="projects.project",
            ),
            preserve_default=False,
        ),
    ]
