# Generated by Django 4.2.20 on 2025-04-12 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenditure", "0002_remove_operationalexpenditure_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operationalexpenditure",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="provisionaryexpenditure",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="regularexpenditure",
            options={"ordering": ["-updated_at"]},
        ),
    ]
