# Generated by Django 4.2.20 on 2026-05-01 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mastermariner", "0001_initial"),
        ("expenditure", "0003_alter_operationalexpenditure_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalexpenditure",
            name="master_mariner",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the master mariner associated with this mariner cost",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operational_expenditures",
                to="mastermariner.mastermariner",
                verbose_name="Master Mariner",
            ),
        ),
    ]
