# Generated by Django 4.2.20 on 2026-03-03 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MasterMariner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Individual name",
                        max_length=100,
                        verbose_name="MasterMariner Name",
                    ),
                ),
                (
                    "nid",
                    models.CharField(
                        help_text="Government-issued national identification number",
                        max_length=20,
                        unique=True,
                        verbose_name="National ID",
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("DIVORCED", "Divorced"),
                            ("WIDOWED", "Widowed"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Marital Status",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        help_text="Official job title/position",
                        max_length=100,
                        verbose_name="Designation",
                    ),
                ),
                (
                    "join_date",
                    models.DateField(auto_now_add=True, verbose_name="Joining Date"),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary contact email",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "address",
                    models.TextField(max_length=200, verbose_name="Current Address"),
                ),
                (
                    "bkash",
                    models.CharField(
                        blank=True,
                        help_text="Mobile banking number for payments",
                        max_length=15,
                        null=True,
                        verbose_name="bKash Number",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Bank Name"
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        help_text="Bank account number for salary",
                        max_length=30,
                        null=True,
                        verbose_name="Account Number",
                    ),
                ),
            ],
            options={
                "verbose_name": "MasterMariner",
                "verbose_name_plural": "MasterMariners",
                "ordering": ["name"],
                "permissions": [
                    ("can_view_sensitive_data", "Can view sensitive Mastermariner data")
                ],
            },
        ),
    ]
