# Generated by Django 4.2.20 on 2025-04-08 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(max_length=10)),
                ("invoice_no", models.CharField(max_length=20)),
                ("invoice_date", models.DateField()),
                ("report_no", models.CharField(max_length=20)),
                ("report_date", models.DateField()),
                ("task1_desc", models.CharField(max_length=80)),
                (
                    "task1_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=11),
                ),
                ("task2_desc", models.CharField(max_length=80)),
                (
                    "task2_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=11),
                ),
                ("task3_desc", models.CharField(max_length=80)),
                (
                    "task3_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=11),
                ),
                ("task4_desc", models.CharField(max_length=80)),
                (
                    "task4_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=11),
                ),
                ("task5_desc", models.CharField(max_length=80)),
                (
                    "task5_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=11),
                ),
                ("task6_desc", models.CharField(default="", max_length=80)),
                (
                    "task6_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=11),
                ),
                ("task7_desc", models.CharField(default="", max_length=80)),
                (
                    "task7_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=11),
                ),
                ("job_order_no", models.CharField(default="", max_length=20)),
                ("shipper", models.CharField(default="", max_length=200)),
                ("buyer", models.CharField(default="", max_length=200)),
                ("cargo", models.CharField(default="", max_length=80)),
                ("bl_qtn", models.CharField(default="", max_length=80)),
                ("ins_qtn", models.CharField(default="", max_length=80)),
                ("date_of_ins", models.CharField(default="", max_length=80)),
                ("plc_of_ins", models.CharField(default="", max_length=80)),
                (
                    "sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=11),
                ),
                (
                    "recieved",
                    models.DecimalField(decimal_places=2, default=0, max_digits=11),
                ),
                (
                    "vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=11),
                ),
                (
                    "total_recieved",
                    models.DecimalField(decimal_places=2, default=0, max_digits=11),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_entry",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
