# Generated by Django 4.2.20 on 2025-04-12 05:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_delete_operationalcost_and_more"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_no", models.CharField(max_length=50, unique=True)),
                ("invoice_date", models.DateField()),
                ("report_no", models.CharField(max_length=20)),
                ("report_date", models.DateField()),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("TK.", "Bangladeshi Taka"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("job_order_no", models.CharField(default="", max_length=20)),
                ("shipper", models.CharField(default="", max_length=200)),
                ("buyer", models.CharField(default="", max_length=200)),
                ("cargo", models.CharField(default="", max_length=80)),
                ("bl_qtn", models.CharField(default="", max_length=80)),
                ("ins_qtn", models.CharField(default="", max_length=80)),
                ("date_of_ins", models.CharField(default="", max_length=80)),
                ("plc_of_ins", models.CharField(default="", max_length=80)),
                (
                    "recieved_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_entry",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="sales.sale",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="SalesEntry",
        ),
    ]
