# Generated by Django 4.2.20 on 2025-05-03 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_delete_operationalcost_and_more"),
        ("sales", "0003_alter_sale_bl_qtn_alter_sale_buyer_alter_sale_cargo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_entry",
                to="projects.project",
            ),
        ),
    ]
