# Generated by Django 4.2.20 on 2025-05-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_alter_sale_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="invoice_no",
            field=models.CharField(max_length=50),
        ),
    ]
