# Generated by Django 4.2.20 on 2025-05-05 04:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_alter_sale_invoice_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("BDT", "Bangladeshi Taka"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="recieved_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
